#! /bin/sh
. "${HOME}/.cache/wal/colors.sh"

sxhkd &

bspc monitor DVI-I-1 -d 6 7 8 9 0
bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#feh --bg-scale ~/Pictures/wp8.jpg
wal -i ~/Pictures/wp6.jpg -a 5 -n
